language: node_js

branches:
  only:
    - deploy

node_js:
  - 8

cache:
  directories:
  - node_modules # NPM packages

install:
  - npm install -g webpack
  - npm install

script:
  - npm run test
  - npm run build